const autorizaciones = [
    {
        nroAutorizacion: 1,
        estado: 'aceptada',
        integrante: 'Santiago Solari',
        medico: 'Dr. Juan Perez',
        fechaPrevista: '2010-07-15',
        lugar: 'Hospital Central',
    },
    {
        nroAutorizacion: 30,
        estado: 'observacion',
        integrante: 'Lucía Fernández',
        medico: 'Dr. Pablo Torres',
        fechaPrevista: '2010-10-02',
        lugar: 'Hospital Central',
    },
    {
        nroAutorizacion: 29,
        estado: 'pendiente',
        integrante: 'Valentina Castro',
        medico: 'Dr. Gustavo López',
        fechaPrevista: '2011-08-30',
        lugar: 'Sanatorio Belgrano',
    },
    {
        nroAutorizacion: 28,
        estado: 'aceptada',
        integrante: 'Matías López',
        medico: 'Dra. Carla Gómez',
        fechaPrevista: '2012-04-07',
        lugar: 'Hospital Central',
    },
    {
        nroAutorizacion: 27,
        estado: 'rechazada',
        integrante: 'Lucía Fernández',
        medico: 'Dr. Pablo Torres',
        fechaPrevista: '2013-11-13',
        lugar: 'Hospital General',
    },
    {
        nroAutorizacion: 26,
        estado: 'observacion',
        integrante: 'Valentina Castro',
        medico: 'Dr. Gustavo López',
        fechaPrevista: '2014-02-28',
        lugar: 'Centro Médico Norte',
    },
    {
        nroAutorizacion: 2,
        estado: 'rechazada',
        integrante: 'Santiago Solari',
        medico: 'Dr. Juan Perez',
        fechaPrevista: '2015-07-15',
        lugar: 'Hospital Central',
    },
    {
        nroAutorizacion: 25,
        estado: 'aceptada',
        integrante: 'Matías López',
        medico: 'Dra. Carla Gómez',
        fechaPrevista: '2015-07-19',
        lugar: 'Clínica Norte',
    },
    {
        nroAutorizacion: 24,
        estado: 'pendiente',
        integrante: 'Lucía Fernández',
        medico: 'Dr. Pablo Torres',
        fechaPrevista: '2016-05-09',
        lugar: 'Hospital Central',
    },
    {
        nroAutorizacion: 14,
        estado: 'rechazada',
        integrante: 'Federico Álvarez',
        medico: 'Dr. Ramiro Campos',
        fechaPrevista: '2017-06-19',
        lugar: 'Sanatorio Belgrano',
    },
    {
        nroAutorizacion: 23,
        estado: 'rechazada',
        integrante: 'Valentina Castro',
        medico: 'Dr. Gustavo López',
        fechaPrevista: '2017-09-18',
        lugar: 'Clínica del Este',
    },
    {
        nroAutorizacion: 22,
        estado: 'aceptada',
        integrante: 'Matías López',
        medico: 'Dr. Pablo Torres',
        fechaPrevista: '2018-03-25',
        lugar: 'Sanatorio San Martín',
    },
    {
        nroAutorizacion: 10,
        estado: 'rechazada',
        integrante: 'Martín García',
        medico: 'Dr. Esteban Rojas',
        fechaPrevista: '2018-08-25',
        lugar: 'Clínica del Este',
    },
    {
        nroAutorizacion: 9,
        estado: 'observacion',
        integrante: 'Camila Romero',
        medico: 'Dra. Laura Méndez',
        fechaPrevista: '2019-12-14',
        lugar: 'Hospital Central',
    },
    {
        nroAutorizacion: 21,
        estado: 'observacion',
        integrante: 'Lucía Fernández',
        medico: 'Dra. Carla Gómez',
        fechaPrevista: '2019-12-20',
        lugar: 'Hospital Central',
    },
    {
        nroAutorizacion: 11,
        estado: 'pendiente',
        integrante: 'Sofía Morales',
        medico: 'Dra. Paula Benítez',
        fechaPrevista: '2020-01-17',
        lugar: 'Hospital General',
    },
    {
        nroAutorizacion: 3,
        estado: 'pendiente',
        integrante: 'Santiago Solari',
        medico: 'Dr. Juan Perez',
        fechaPrevista: '2020-07-15',
        lugar: 'Hospital Central',
    },
    {
        nroAutorizacion: 20,
        estado: 'pendiente',
        integrante: 'Valentina Castro',
        medico: 'Dr. Gustavo López',
        fechaPrevista: '2020-10-05',
        lugar: 'Hospital de la Rivera',
    },
    {
        nroAutorizacion: 8,
        estado: 'aceptada',
        integrante: 'Julián Herrera',
        medico: 'Dr. Pablo Torres',
        fechaPrevista: '2021-05-08',
        lugar: 'Clínica Norte',
    },
    {
        nroAutorizacion: 19,
        estado: 'aceptada',
        integrante: 'Matías López',
        medico: 'Dra. Carla Gómez',
        fechaPrevista: '2021-06-11',
        lugar: 'Centro Médico Norte',
    },
    {
        nroAutorizacion: 18,
        estado: 'rechazada',
        integrante: 'Lucía Fernández',
        medico: 'Dr. Pablo Torres',
        fechaPrevista: '2022-02-15',
        lugar: 'Clínica Norte',
    },
    {
        nroAutorizacion: 7,
        estado: 'rechazada',
        integrante: 'Valentina Castro',
        medico: 'Dra. Mariana Silva',
        fechaPrevista: '2022-09-30',
        lugar: 'Sanatorio San Martín',
    },
    {
        nroAutorizacion: 6,
        estado: 'pendiente',
        integrante: 'Matías López',
        medico: 'Dr. Ricardo Domínguez',
        fechaPrevista: '2023-03-12',
        lugar: 'Hospital de la Rivera',
    },
    {
        nroAutorizacion: 17,
        estado: 'observacion',
        integrante: 'Valentina Castro',
        medico: 'Dr. Gustavo López',
        fechaPrevista: '2023-04-10',
        lugar: 'Hospital General',
    },
    {
        nroAutorizacion: 13,
        estado: 'observacion',
        integrante: 'Carla Ruiz',
        medico: 'Dra. Jimena Duarte',
        fechaPrevista: '2023-10-10',
        lugar: 'Hospital San José',
    },
    {
        nroAutorizacion: 12,
        estado: 'aceptada',
        integrante: 'Tomás Vega',
        medico: 'Dr. Gustavo López',
        fechaPrevista: '2024-02-28',
        lugar: 'Centro Médico Norte',
    },
    {
        nroAutorizacion: 16,
        estado: 'pendiente',
        integrante: 'Matías López',
        medico: 'Dra. Carla Gómez',
        fechaPrevista: '2024-08-22',
        lugar: 'Clínica del Sur',
    },
    {
        nroAutorizacion: 5,
        estado: 'aceptada',
        integrante: 'Lucía Fernández',
        medico: 'Dra. Carla Gómez',
        fechaPrevista: '2024-11-20',
        lugar: 'Clínica del Sur',
    },
    {
        nroAutorizacion: 4,
        estado: 'observacion',
        integrante: 'Santiago Solari',
        medico: 'Dr. Juan Perez',
        fechaPrevista: '2025-07-15',
        lugar: 'Hospital Central',
    },
    {
        nroAutorizacion: 15,
        estado: 'aceptada',
        integrante: 'Lucía Fernández',
        medico: 'Dr. Pablo Torres',
        fechaPrevista: '2025-09-01',
        lugar: 'Hospital Central',
    },
];




export default autorizaciones