const reintegros = [
    {
        id: '0015',
        fechaDeCarga: '2024-01-15',
        fechaDePrestacion: '2024-01-20',
        integrante: 'Hijitus',
        medico: 'Dr. Roberto García',
        especialidad: 'Cirujano',
        lugarDeAtencion: 'Hospital de San Miguel',
        observaciones: 'Operación de apendicitis',
        monto: 60.255,
        estado: 'Pago'
    },
    {
        id: '0016',
        fechaDeCarga: '2024-03-10',
        fechaDePrestacion: '2024-02-28',
        integrante: 'Larguirucho',
        medico: 'Dra. Ana López',
        especialidad: 'Cirujano',
        lugarDeAtencion: 'Hospital de San Miguel',
        observaciones: 'Consulta pre-operatoria',
        monto: 20.255,
        estado: 'Rechazado'
    },
    {
        id: '0017',
        fechaDeCarga: '2024-05-20',
        fechaDePrestacion: '2024-05-15',
        integrante: 'Pichichus',
        medico: 'Dr. Roberto García',
        especialidad: 'Cirujano',
        lugarDeAtencion: 'Hospital de San Miguel',
        observaciones: 'Estudios de laboratorio',
        monto: 140.255,
        estado: 'Pendiente'
    },
    {
        id: '0018',
        fechaDeCarga: '2024-08-01',
        fechaDePrestacion: '2024-07-25',
        integrante: 'Súper Hijitus',
        medico: 'Dr. Roberto García',
        especialidad: 'Cirujano',
        lugarDeAtencion: 'Hospital de San Miguel',
        observaciones: 'Revisión general',
        monto: 10,
        estado: 'Pendiente'
    },
    {
        id: '0019',
        fechaDeCarga: '2024-10-15',
        fechaDePrestacion: '2024-10-10',
        integrante: 'Neurus',
        medico: 'Dr. Carlos Sánchez',
        especialidad: 'Neurólogo',
        lugarDeAtencion: 'Clínica del Norte',
        observaciones: 'Consulta de rutina',
        monto: 85.00,
        estado: 'Pendiente'
    },
    {
        id: '0020',
        fechaDeCarga: '2024-11-30',
        fechaDePrestacion: '2024-11-28',
        integrante: 'Pucho',
        medico: 'Dra. Laura Torres',
        especialidad: 'Odontólogo',
        lugarDeAtencion: 'Consultorio Privado',
        observaciones: 'Extracción de muela',
        monto: 120.50,
        estado: 'Pago'
    },
    {
        id: '0021',
        fechaDeCarga: '2025-01-05',
        fechaDePrestacion: '2025-01-02',
        integrante: 'Serrucho',
        medico: 'Dr. Jorge Fernández',
        especialidad: 'Traumatólogo',
        lugarDeAtencion: 'Hospital Italiano',
        observaciones: 'Placa de rayos X y consulta',
        monto: 45.75,
        estado: 'Rechazado'
    },
    {
        id: '0022',
        fechaDeCarga: '2025-02-20',
        fechaDePrestacion: '2025-02-18',
        integrante: 'Oaky',
        medico: 'Dra. Sofía Giménez',
        especialidad: 'Cardiólogo',
        lugarDeAtencion: 'Favaloro',
        observaciones: 'Electrocardiograma',
        monto: 210.00,
        estado: 'Pendiente'
    },
    {
        id: '0023',
        fechaDeCarga: '2025-03-15',
        fechaDePrestacion: '2025-03-12',
        integrante: 'Gold Silver',
        medico: 'Dr. Diego Ruiz',
        especialidad: 'Oftalmólogo',
        lugarDeAtencion: 'Centro de la Visión',
        observaciones: 'Renovación de lentes',
        monto: 300.00,
        estado: 'Pago'
    },
    {
        id: '0024',
        fechaDeCarga: '2025-04-10',
        fechaDePrestacion: '2025-04-05',
        integrante: 'Cachavacha',
        medico: 'Dra. Valeria Castro',
        especialidad: 'Homeópata',
        lugarDeAtencion: 'Herboristería Mágica',
        observaciones: 'Tratamiento alternativo',
        monto: 75.00,
        estado: 'Rechazado'
    },
    {
        id: '0025',
        fechaDeCarga: '2025-05-01',
        fechaDePrestacion: '2025-04-28',
        integrante: 'Neurus',
        medico: 'Dr. Carlos Sánchez',
        especialidad: 'Neurólogo',
        lugarDeAtencion: 'Clínica del Norte',
        observaciones: 'Segunda opinión',
        monto: 90.00,
        estado: 'Pendiente'
    },
    {
        id: '0026',
        fechaDeCarga: '2025-06-12',
        fechaDePrestacion: '2025-06-10',
        integrante: 'Pichichus',
        medico: 'Dra. Mariana Herrera',
        especialidad: 'Pediatra',
        lugarDeAtencion: 'Hospital de Niños',
        observaciones: 'Control de crecimiento',
        monto: 50.00,
        estado: 'Pago'
    },
    {
        id: '0027',
        fechaDeCarga: '2025-07-07',
        fechaDePrestacion: '2025-07-05',
        integrante: 'Hijitus',
        medico: 'Dr. Jorge Fernández',
        especialidad: 'Traumatólogo',
        lugarDeAtencion: 'Hospital Italiano',
        observaciones: 'Fisioterapia, 3 sesiones',
        monto: 150.00,
        estado: 'Pendiente'
    },
    {
        id: '0028',
        fechaDeCarga: '2025-08-08',
        fechaDePrestacion: '2025-08-06',
        integrante: 'Larguirucho',
        medico: 'Dra. Laura Torres',
        especialidad: 'Odontólogo',
        lugarDeAtencion: 'Consultorio Privado',
        observaciones: 'Limpieza dental',
        monto: 70.00,
        estado: 'Pago'
    },
    {
        id: '0029',
        fechaDeCarga: '2025-09-09',
        fechaDePrestacion: '2025-09-07',
        integrante: 'Súper Hijitus',
        medico: 'Dra. Sofía Giménez',
        especialidad: 'Cardiólogo',
        lugarDeAtencion: 'Favaloro',
        observaciones: 'Estudios completos',
        monto: 400.00,
        estado: 'Pendiente'
    },
    {
        id: '0030',
        fechaDeCarga: '2025-10-01',
        fechaDePrestacion: '2025-09-28',
        integrante: 'Pucho',
        medico: 'Dr. Jorge Fernández',
        especialidad: 'Traumatólogo',
        lugarDeAtencion: 'Hospital Italiano',
        observaciones: 'Venda y consulta',
        monto: 35.00,
        estado: 'Rechazado'
    },
    {
        id: '0031',
        fechaDeCarga: '2025-10-02',
        fechaDePrestacion: '2025-09-30',
        integrante: 'Serrucho',
        medico: 'Dra. Mariana Herrera',
        especialidad: 'Pediatra',
        lugarDeAtencion: 'Hospital de Niños',
        observaciones: 'Vacunas',
        monto: 25.00,
        estado: 'Pago'
    },
    {
        id: '0032',
        fechaDeCarga: '2025-10-03',
        fechaDePrestacion: '2025-10-01',
        integrante: 'Oaky',
        medico: 'Dr. Diego Ruiz',
        especialidad: 'Oftalmólogo',
        lugarDeAtencion: 'Centro de la Visión',
        observaciones: 'Lentes de contacto',
        monto: 250.00,
        estado: 'Pendiente'
    },
    {
        id: '0033',
        fechaDeCarga: '2025-10-04',
        fechaDePrestacion: '2025-10-03',
        integrante: 'Gold Silver',
        medico: 'Dra. Valeria Castro',
        especialidad: 'Homeópata',
        lugarDeAtencion: 'Herboristería Mágica',
        observaciones: 'Consulta de seguimiento',
        monto: 60.00,
        estado: 'Pago'
    },
    {
        id: '0034',
        fechaDeCarga: '2025-10-05',
        fechaDePrestacion: '2025-10-04',
        integrante: 'Cachavacha',
        medico: 'Dr. Roberto García',
        especialidad: 'Cirujano',
        lugarDeAtencion: 'Hospital de San Miguel',
        observaciones: 'Operación menor',
        monto: 500.00,
        estado: 'Pendiente'
    }
];

export default reintegros;